import {
  FaPython,
  FaJs,
  FaReact,
  FaHtml5,
  FaCss3Alt,
  FaJava,
  FaNodeJs,
  FaGitAlt,
  FaGithub,
  FaDatabase,
  FaCuttlefish,
  FaDocker,
  FaAws,
  FaFigma,
  FaCode,
} from "react-icons/fa";
import {
  SiExpress,
  SiMongodb,
  SiDjango,
  SiFlask,
  SiTensorflow,
  SiScikitlearn,
  SiTypescript,
  SiTailwindcss,
  SiNextdotjs,
} from "react-icons/si";
const skillIcons = {
  javascript: FaJs,
  typescript: SiTypescript,
  python: FaPython,
  react: FaReact,
  html: FaHtml5,
  css: FaCss3Alt,
  java: FaJava,
  nodejs: FaNodeJs,
  express: SiExpress,
  mongodb: SiMongodb,
  django: SiDjango,
  flask: SiFlask,
  ai: SiTensorflow,
  ml: SiScikitlearn,
  git: FaGitAlt,
  github: FaGithub,
  sql: FaDatabase,
  c: FaCuttlefish,
  "c++": (props) => <img src="/cppicon.svg" alt="C++" {...props} />,
  cpp: (props) => <img src="/cppicon.svg" alt="C++" {...props} />,
  docker: FaDocker,
  aws: FaAws,
  figma: FaFigma,
  tailwind: SiTailwindcss,
  nextjs: SiNextdotjs,
};

export { skillIcons, FaCode };
